// 公共生信数据资源注册表：每个服务声明 baseUrl、常用端点（path 中 {param} 为
// 路径占位符，调用时由 invokeWebApi 做模板替换）和最轻量的真实健康探针。
// 只收录有公开 API 的资源；个别服务无稳定 JSON API 时在 authNote 如实说明
// （返回 HTML/TSV、站点维护窗口、需注册等），不写假端点。

export type WebApiCategory =
  | 'genes-genomes'
  | 'proteins'
  | 'pathways'
  | 'compounds'
  | 'variants'
  | 'expression'
  | 'literature'
  | 'taxonomy'
  | 'plants'
  | 'microbes';

export const WEB_API_CATEGORY_LABELS: Record<WebApiCategory, { zh: string; en: string }> = {
  'genes-genomes': { zh: '基因与基因组', en: 'Genes & Genomes' },
  proteins: { zh: '蛋白与结构', en: 'Proteins & Structures' },
  pathways: { zh: '通路与互作', en: 'Pathways & Interactions' },
  compounds: { zh: '化合物与药物', en: 'Compounds & Drugs' },
  variants: { zh: '变异与临床', en: 'Variants & Clinical' },
  expression: { zh: '表达与单细胞', en: 'Expression & Single-cell' },
  literature: { zh: '文献与检索', en: 'Literature & Search' },
  taxonomy: { zh: '物种与分类', en: 'Species & Taxonomy' },
  plants: { zh: '植物', en: 'Plants' },
  microbes: { zh: '微生物与宏基因组', en: 'Microbes & Metagenomics' },
};

export interface WebApiParam {
  name: string;
  required?: boolean;
  description: string;
  /** 缺省推断：出现在 path 模板里的为 path；GET 其余为 query，POST 其余为 body。 */
  in?: 'path' | 'query' | 'body';
}

export interface WebApiEndpoint {
  id: string;
  name: string;
  method: 'GET' | 'POST';
  /** path 里 {param} 占位，调用时 URL 编码后替换。 */
  path: string;
  description: string;
  params?: WebApiParam[];
}

export interface WebApiProbe {
  /** 指向 endpoints 中某个端点 id。 */
  endpoint: string;
  params?: Record<string, string>;
  expect: { status?: number; contains?: string };
}

export interface WebApiService {
  id: string;
  name: string;
  category: WebApiCategory;
  baseUrl: string;
  description: string;
  homepage: string;
  docsUrl: string;
  authNote?: string;
  endpoints: WebApiEndpoint[];
  probe: WebApiProbe;
}

const JSON_QUERY: WebApiParam = {
  name: 'content-type',
  description: '传 application/json 以获取 JSON 响应',
  in: 'query',
};

export const WEB_API_SERVICES: WebApiService[] = [
  {
    id: 'ncbi-eutils',
    name: 'NCBI E-utilities',
    category: 'genes-genomes',
    baseUrl: 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils',
    description: 'NCBI 全系数据库（PubMed、Gene、nuccore、assembly 等）检索与获取接口',
    homepage: 'https://www.ncbi.nlm.nih.gov/',
    docsUrl: 'https://www.ncbi.nlm.nih.gov/books/NBK25501/',
    endpoints: [
      {
        id: 'esearch',
        name: 'ESearch 检索',
        method: 'GET',
        path: '/esearch.fcgi',
        description: '按关键词检索某个 NCBI 数据库，返回 UID 列表',
        params: [
          { name: 'db', required: true, description: '数据库名，如 pubmed / gene / nuccore / assembly' },
          { name: 'term', required: true, description: '检索式，如 BRCA1[Gene Name] AND human[Organism]' },
          { name: 'retmode', description: '传 json 获取 JSON 响应' },
          { name: 'retmax', description: '最多返回条数，默认 20' },
        ],
      },
      {
        id: 'esummary',
        name: 'ESummary 摘要',
        method: 'GET',
        path: '/esummary.fcgi',
        description: '按 UID 列表取条目摘要（标题、命名、来源等）',
        params: [
          { name: 'db', required: true, description: '数据库名' },
          { name: 'id', required: true, description: '逗号分隔的 UID 列表' },
          { name: 'retmode', description: '传 json 获取 JSON 响应' },
        ],
      },
      {
        id: 'efetch',
        name: 'EFetch 全文获取',
        method: 'GET',
        path: '/efetch.fcgi',
        description: '按 UID 获取记录全文（GenBank/FASTA/XML 等），可按坐标取区段',
        params: [
          { name: 'db', required: true, description: '数据库名' },
          { name: 'id', required: true, description: '逗号分隔的 UID 列表' },
          { name: 'rettype', description: '记录类型，如 fasta / gb / abstract' },
          { name: 'retmode', description: '如 text / xml' },
          { name: 'seq_start', description: '区段起点（1 起始，可选）' },
          { name: 'seq_stop', description: '区段终点（可选）' },
          { name: 'strand', description: '链：1=正链，2=负链（可选）' },
        ],
      },
    ],
    probe: {
      endpoint: 'esearch',
      params: { db: 'pubmed', term: 'cancer', retmode: 'json', retmax: '1' },
      expect: { contains: 'esearchresult' },
    },
  },
  {
    id: 'ensembl',
    name: 'Ensembl REST',
    category: 'genes-genomes',
    baseUrl: 'https://rest.ensembl.org',
    description: 'Ensembl 脊椎动物基因组注释：基因 lookup、序列获取、区域 overlap',
    homepage: 'https://www.ensembl.org/',
    docsUrl: 'https://rest.ensembl.org/',
    endpoints: [
      {
        id: 'lookup-id',
        name: '按 ID 查询',
        method: 'GET',
        path: '/lookup/id/{id}',
        description: '按 Ensembl 稳定 ID 查基因/转录本/外显子注释',
        params: [
          { name: 'id', required: true, description: 'Ensembl ID，如 ENSG00000157764', in: 'path' },
          JSON_QUERY,
        ],
      },
      {
        id: 'sequence-id',
        name: '按 ID 取序列',
        method: 'GET',
        path: '/sequence/id/{id}',
        description: '获取 Ensembl ID 对应的基因组/CDS/蛋白序列',
        params: [
          { name: 'id', required: true, description: 'Ensembl ID', in: 'path' },
          { name: 'type', description: 'genomic / cds / protein，默认 genomic' },
          JSON_QUERY,
        ],
      },
      {
        id: 'overlap-region',
        name: '区域特征查询',
        method: 'GET',
        path: '/overlap/region/{species}/{region}',
        description: '查询某物种基因组区段上的基因/转录本/变异等特征',
        params: [
          { name: 'species', required: true, description: '物种，如 human / homo_sapiens', in: 'path' },
          { name: 'region', required: true, description: '区段，如 7:140424943-140624564', in: 'path' },
          { name: 'feature', description: 'gene / transcript / cds / variation 等' },
          JSON_QUERY,
        ],
      },
    ],
    probe: {
      endpoint: 'lookup-id',
      params: { id: 'ENSG00000157764', 'content-type': 'application/json' },
      expect: { contains: 'BRAF' },
    },
  },
  {
    id: 'plantreactome',
    name: 'Plant Reactome 植物通路',
    category: 'plants',
    baseUrl: 'https://plantreactome.gramene.org',
    description: 'Plant Reactome 植物通路数据库：水稻/拟南芥/玉米等物种的通路、反应与蛋白（Ensembl Plants REST 从本网络不可达，植物注释查询走 Gramene/phytozome）',
    homepage: 'https://plantreactome.gramene.org/',
    docsUrl: 'https://plantreactome.gramene.org/ContentService/',
    endpoints: [
      {
        id: 'search',
        name: '通路/蛋白检索',
        method: 'GET',
        path: '/ContentService/search/query',
        description: '按关键词检索植物通路、反应与蛋白',
        params: [
          { name: 'query', required: true, description: '关键词，如 phytochrome' },
          { name: 'types', description: '类型过滤，如 Protein / Pathway' },
          { name: 'species', description: '物种过滤，如 Oryza sativa' },
        ],
      },
      {
        id: 'pathway',
        name: '通路详情',
        method: 'GET',
        path: '/ContentService/data/pathway/{id}',
        description: '按 Reactome id 取通路详情',
        params: [{ name: 'id', required: true, description: '如 R-OSA-2744345', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { query: 'phytochrome', types: 'Protein' },
      expect: { contains: 'results' },
    },
  },
  {
    id: 'uniprot',
    name: 'UniProtKB REST',
    category: 'proteins',
    baseUrl: 'https://rest.uniprot.org',
    description: 'UniProt 蛋白知识库：序列、功能注释、ID 映射',
    homepage: 'https://www.uniprot.org/',
    docsUrl: 'https://www.uniprot.org/help/programmatic_access',
    endpoints: [
      {
        id: 'search',
        name: '蛋白检索',
        method: 'GET',
        path: '/uniprotkb/search',
        description: '按 UniProt 查询语法检索蛋白条目',
        params: [
          { name: 'query', required: true, description: '查询式，如 gene:BRCA1 AND organism_id:9606' },
          { name: 'size', description: '返回条数，默认 25，最大 500' },
          { name: 'format', description: 'json / tsv / fasta，默认 json' },
          { name: 'fields', description: 'tsv 时的列，如 accession,gene_names,protein_name' },
        ],
      },
      {
        id: 'entry',
        name: '按登录号取条目',
        method: 'GET',
        path: '/uniprotkb/{accession}',
        description: '按 UniProt 登录号取完整蛋白条目（JSON）',
        params: [{ name: 'accession', required: true, description: 'UniProt 登录号，如 P69905', in: 'path' }],
      },
      {
        id: 'entry-fasta',
        name: '按登录号取 FASTA 序列',
        method: 'GET',
        path: '/uniprotkb/{accession}.fasta',
        description: '按 UniProt 登录号直接取蛋白 FASTA 序列（文本）',
        params: [{ name: 'accession', required: true, description: 'UniProt 登录号，如 P69905', in: 'path' }],
      },
      {
        id: 'idmapping-run',
        name: 'ID 映射提交',
        method: 'POST',
        path: '/idmapping/run',
        description: '提交一批 ID 的跨库映射任务（如 UniProtKB_AC-ID -> Ensembl），返回 jobId',
        params: [
          { name: 'from', required: true, description: '源库，如 UniProtKB_AC-ID', in: 'body' },
          { name: 'to', required: true, description: '目标库，如 Ensembl', in: 'body' },
          { name: 'ids', required: true, description: '逗号分隔的 ID 列表', in: 'body' },
        ],
      },
      {
        id: 'idmapping-status',
        name: 'ID 映射状态',
        method: 'GET',
        path: '/idmapping/status/{jobId}',
        description: '查询 ID 映射任务状态；完成后用 /idmapping/results/{jobId} 取结果',
        params: [{ name: 'jobId', required: true, description: 'idmapping-run 返回的任务 ID', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { query: 'insulin', size: '1' },
      expect: { contains: 'results' },
    },
  },
  {
    id: 'interpro',
    name: 'InterPro API',
    category: 'proteins',
    baseUrl: 'https://www.ebi.ac.uk/interpro/api',
    description: 'InterPro 蛋白结构域/家族/功能位点注释',
    homepage: 'https://www.ebi.ac.uk/interpro/',
    docsUrl: 'https://www.ebi.ac.uk/interpro/api/',
    endpoints: [
      {
        id: 'entry',
        name: '按编号查条目',
        method: 'GET',
        path: '/entry/interpro/{accession}',
        description: '按 InterPro 编号查结构域/家族条目',
        params: [{ name: 'accession', required: true, description: 'InterPro 编号，如 IPR000001', in: 'path' }],
      },
      {
        id: 'entries',
        name: '条目检索',
        method: 'GET',
        path: '/entry/interpro',
        description: '检索 InterPro 条目列表',
        params: [
          { name: 'search', description: '关键词' },
          { name: 'page_size', description: '每页条数' },
        ],
      },
      {
        id: 'protein-by-entry',
        name: '条目下的蛋白',
        method: 'GET',
        path: '/protein/reviewed/entry/interpro/{accession}',
        description: '列出带某 InterPro 注释的已审编蛋白',
        params: [
          { name: 'accession', required: true, description: 'InterPro 编号', in: 'path' },
          { name: 'page_size', description: '每页条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'entry',
      params: { accession: 'IPR000001' },
      expect: { contains: 'IPR000001' },
    },
  },
  {
    id: 'pdbe',
    name: 'PDBe API',
    category: 'proteins',
    baseUrl: 'https://www.ebi.ac.uk/pdbe/api',
    description: '欧洲 PDB：结构条目、分子组成、实验方法',
    homepage: 'https://www.ebi.ac.uk/pdbe/',
    docsUrl: 'https://www.ebi.ac.uk/pdbe/pdbe-rest-api',
    endpoints: [
      {
        id: 'entry',
        name: '结构条目',
        method: 'GET',
        path: '/pdb/entry/summary/{pdbId}',
        description: 'PDB 条目概览（标题、分辨率、方法等）',
        params: [{ name: 'pdbId', required: true, description: 'PDB ID，如 1cbs', in: 'path' }],
      },
      {
        id: 'molecules',
        name: '分子组成',
        method: 'GET',
        path: '/pdb/entry/molecules/{pdbId}',
        description: 'PDB 条目中的实体/链/配体信息',
        params: [{ name: 'pdbId', required: true, description: 'PDB ID', in: 'path' }],
      },
      {
        id: 'experiment',
        name: '实验信息',
        method: 'GET',
        path: '/pdb/entry/experiment/{pdbId}',
        description: 'PDB 条目的实验方法细节',
        params: [{ name: 'pdbId', required: true, description: 'PDB ID', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'entry',
      params: { pdbId: '1cbs' },
      expect: { contains: '1cbs' },
    },
  },
  {
    id: 'rcsb',
    name: 'RCSB PDB Data API',
    category: 'proteins',
    baseUrl: 'https://data.rcsb.org/rest/v1',
    description: 'RCSB PDB 结构数据：条目与聚合物实体',
    homepage: 'https://www.rcsb.org/',
    docsUrl: 'https://data.rcsb.org/',
    endpoints: [
      {
        id: 'entry',
        name: '结构条目',
        method: 'GET',
        path: '/core/entry/{pdbId}',
        description: 'PDB 条目核心数据（结构标题、实验、引用）',
        params: [{ name: 'pdbId', required: true, description: 'PDB ID，如 4HHB', in: 'path' }],
      },
      {
        id: 'polymer-entity',
        name: '聚合物实体',
        method: 'GET',
        path: '/core/polymer_entity/{pdbId}/{entityId}',
        description: 'PDB 中某条链的序列与注释',
        params: [
          { name: 'pdbId', required: true, description: 'PDB ID', in: 'path' },
          { name: 'entityId', required: true, description: '实体编号，如 1', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'entry',
      params: { pdbId: '4HHB' },
      expect: { contains: '4HHB' },
    },
  },
  {
    id: 'alphafold',
    name: 'AlphaFold DB API',
    category: 'proteins',
    baseUrl: 'https://alphafold.ebi.ac.uk/api',
    description: 'AlphaFold 预测结构：按 UniProt 登录号查预测模型与置信度',
    homepage: 'https://alphafold.ebi.ac.uk/',
    docsUrl: 'https://alphafold.ebi.ac.uk/api-docs',
    endpoints: [
      {
        id: 'prediction',
        name: '预测模型',
        method: 'GET',
        path: '/prediction/{accession}',
        description: '按 UniProt 登录号取 AlphaFold 预测（PDB/mmCIF 下载链接、pLDDT）',
        params: [{ name: 'accession', required: true, description: 'UniProt 登录号，如 P69905', in: 'path' }],
      },
      {
        id: 'uniprot-summary',
        name: '预测摘要',
        method: 'GET',
        path: '/uniprot/summary/{accession}.json',
        description: '按 UniProt 登录号取该蛋白的全部 AlphaFold 预测摘要',
        params: [{ name: 'accession', required: true, description: 'UniProt 登录号', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'prediction',
      params: { accession: 'P69905' },
      expect: { contains: 'P69905' },
    },
  },
  {
    id: 'geneontology',
    name: 'Gene Ontology API',
    category: 'genes-genomes',
    baseUrl: 'https://api.geneontology.org/api',
    description: 'GO 官方 API：本体术语查询与基因产物功能注释检索',
    homepage: 'http://geneontology.org/',
    docsUrl: 'https://api.geneontology.org/api',
    endpoints: [
      {
        id: 'term',
        name: 'GO 术语',
        method: 'GET',
        path: '/ontology/term/{id}',
        description: '按 GO ID 查术语定义、层级',
        params: [{ name: 'id', required: true, description: 'GO ID，如 GO:0008150', in: 'path' }],
      },
      {
        id: 'autocomplete',
        name: '实体自动补全',
        method: 'GET',
        path: '/search/entity/autocomplete/{term}',
        description: '按关键词补全 GO 基因产物/术语实体',
        params: [{ name: 'term', required: true, description: '关键词，如 insulin', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'term',
      params: { id: 'GO:0008150' },
      expect: { contains: 'biological_process' },
    },
  },
  {
    id: 'quickgo',
    name: 'QuickGO API',
    category: 'genes-genomes',
    baseUrl: 'https://www.ebi.ac.uk/QuickGO/services',
    description: 'EBI GO 注释库：按基因产物/GO 术语检索功能注释',
    homepage: 'https://www.ebi.ac.uk/QuickGO/',
    docsUrl: 'https://www.ebi.ac.uk/QuickGO/api/index.html',
    endpoints: [
      {
        id: 'annotation-search',
        name: '注释检索',
        method: 'GET',
        path: '/annotation/search',
        description: '按基因产物 ID 或 GO 术语检索 GO 注释',
        params: [
          { name: 'geneProductId', description: '基因产物 ID，如 UniProtKB:P69905' },
          { name: 'goId', description: 'GO ID，如 GO:0008150' },
          { name: 'limit', description: '返回条数，默认 25' },
        ],
      },
      {
        id: 'term',
        name: 'GO 术语详情',
        method: 'GET',
        path: '/ontology/go/terms/{ids}',
        description: '按 GO ID（可逗号分隔多个）取术语详情',
        params: [{ name: 'ids', required: true, description: 'GO ID 列表，如 GO:0008150', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'term',
      params: { ids: 'GO:0008150' },
      expect: { contains: 'biological_process' },
    },
  },
  {
    id: 'reactome',
    name: 'Reactome Content Service',
    category: 'pathways',
    baseUrl: 'https://reactome.org/ContentService',
    description: 'Reactome 通路数据库：通路条目与全文检索',
    homepage: 'https://reactome.org/',
    docsUrl: 'https://reactome.org/dev/content-service',
    endpoints: [
      {
        id: 'entry',
        name: '按 ID 取条目',
        method: 'GET',
        path: '/data/query/{id}',
        description: '按稳定 ID 取通路/反应/分子完整条目',
        params: [{ name: 'id', required: true, description: 'Reactome 稳定 ID，如 R-HSA-199420', in: 'path' }],
      },
      {
        id: 'pathway',
        name: '通路结构',
        method: 'GET',
        path: '/data/pathway/{id}',
        description: '取通路的事件层级（子通路/反应）',
        params: [{ name: 'id', required: true, description: '通路稳定 ID', in: 'path' }],
      },
      {
        id: 'search',
        name: '检索',
        method: 'GET',
        path: '/search/query',
        description: '按关键词检索通路、反应、蛋白',
        params: [
          { name: 'query', required: true, description: '关键词，如 apoptosis' },
          { name: 'species', description: '物种过滤，如 Homo sapiens' },
          { name: 'types', description: '类型过滤，如 Pathway' },
        ],
      },
    ],
    probe: {
      endpoint: 'entry',
      params: { id: 'R-HSA-199420' },
      expect: { contains: '199420' },
    },
  },
  {
    id: 'kegg',
    name: 'KEGG REST',
    category: 'pathways',
    baseUrl: 'https://rest.kegg.jp',
    description: 'KEGG 通路/化合物/基因：find、get、link 操作',
    homepage: 'https://www.kegg.jp/',
    docsUrl: 'https://www.kegg.jp/kegg/rest/keggapi.html',
    authNote: '响应为纯文本/TSV（官方不提供 JSON）；学术用途免费，批量抓取请控制频率',
    endpoints: [
      {
        id: 'find',
        name: '关键词查找',
        method: 'GET',
        path: '/find/{database}/{query}',
        description: '在指定库（compound/pathway/genes/hsa 等）中按关键词找条目',
        params: [
          { name: 'database', required: true, description: '库名，如 compound / pathway / hsa', in: 'path' },
          { name: 'query', required: true, description: '关键词，如 glucose', in: 'path' },
        ],
      },
      {
        id: 'get',
        name: '取条目',
        method: 'GET',
        path: '/get/{entry}',
        description: '按条目号取记录，如 hsa:10458 或 map00010；可加 /aaseq /ntseq /image',
        params: [{ name: 'entry', required: true, description: '条目号，如 hsa:10458 / map00010', in: 'path' }],
      },
      {
        id: 'link',
        name: '跨库关联',
        method: 'GET',
        path: '/link/{target}/{source}',
        description: '查两库条目的对应关系，如 /link/pathway/hsa',
        params: [
          { name: 'target', required: true, description: '目标库，如 pathway', in: 'path' },
          { name: 'source', required: true, description: '源库或具体条目，如 hsa 或 hsa:10458', in: 'path' },
        ],
      },
      {
        id: 'info',
        name: '库版本信息',
        method: 'GET',
        path: '/info/{database}',
        description: '取某 KEGG 数据库的发布版本与统计信息（TSV）',
        params: [{ name: 'database', required: true, description: '库名，如 pathway / kegg', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'info',
      params: { database: 'pathway' },
      expect: { contains: 'KEGG' },
    },
  },
  {
    id: 'string',
    name: 'STRING API',
    category: 'pathways',
    baseUrl: 'https://string-db.org/api',
    description: 'STRING 蛋白互作网络：ID 解析、互作网络、互作伙伴',
    homepage: 'https://string-db.org/',
    docsUrl: 'https://string-db.org/help/api/',
    endpoints: [
      {
        id: 'get-string-ids',
        name: 'ID 解析',
        method: 'GET',
        path: '/{format}/get_string_ids',
        description: '把基因名/蛋白名解析为 STRING 内部 ID',
        params: [
          { name: 'format', required: true, description: '输出格式，通常 json', in: 'path' },
          { name: 'identifiers', required: true, description: '%0d 或空格分隔的名称列表，如 TP53' },
          { name: 'species', description: 'NCBI 物种号，如 9606' },
        ],
      },
      {
        id: 'network',
        name: '互作网络',
        method: 'GET',
        path: '/{format}/network',
        description: '取一组蛋白之间的互作边（得分）',
        params: [
          { name: 'format', required: true, description: 'json 或 tsv', in: 'path' },
          { name: 'identifiers', required: true, description: '%0d 分隔的名称列表' },
          { name: 'species', description: 'NCBI 物种号' },
          { name: 'required_score', description: '最低置信度 0-1000' },
        ],
      },
      {
        id: 'interaction-partners',
        name: '互作伙伴',
        method: 'GET',
        path: '/{format}/interaction_partners',
        description: '取单个蛋白的互作伙伴列表',
        params: [
          { name: 'format', required: true, description: 'json 或 tsv', in: 'path' },
          { name: 'identifiers', required: true, description: '蛋白名，如 TP53' },
          { name: 'species', description: 'NCBI 物种号' },
          { name: 'limit', description: '伙伴数上限' },
        ],
      },
    ],
    probe: {
      endpoint: 'get-string-ids',
      params: { format: 'json', identifiers: 'TP53', species: '9606' },
      expect: { contains: 'TP53' },
    },
  },
  {
    id: 'intact',
    name: 'IntAct API',
    category: 'pathways',
    baseUrl: 'https://www.ebi.ac.uk/intact/ws',
    description: 'IntAct 分子互作数据库：互作子与互作证据检索',
    homepage: 'https://www.ebi.ac.uk/intact/',
    docsUrl: 'https://www.ebi.ac.uk/intact/documentation/',
    authNote: '直连 API 偶发不稳定；失败时可改用 EBI Search 的 intact 域（https://www.ebi.ac.uk/ebisearch/ws/rest/intact?query=...）',
    endpoints: [
      {
        id: 'interactor',
        name: '互作子查询',
        method: 'GET',
        path: '/interactor/findInteractor/{identifier}',
        description: '按 UniProt 登录号/基因名查互作子（分页 JSON）',
        params: [
          { name: 'identifier', required: true, description: '如 P69905 或 brca2', in: 'path' },
          { name: 'page', description: '页码，从 0 开始' },
          { name: 'pageSize', description: '每页条数' },
        ],
      },
      {
        id: 'interactions',
        name: '互作检索',
        method: 'GET',
        path: '/interaction/findInteractions',
        description: '按关键词检索互作证据',
        params: [
          { name: 'query', required: true, description: '关键词，如 brca2' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
          { name: 'firstResult', description: '起始偏移，默认 0' },
          { name: 'maxResults', description: '返回条数上限' },
        ],
      },
    ],
    probe: {
      endpoint: 'interactor',
      params: { identifier: 'P69905', pageSize: '5' },
      expect: { contains: 'content' },
    },
  },
  {
    id: 'complexportal',
    name: 'Complex Portal API',
    category: 'pathways',
    baseUrl: 'https://www.ebi.ac.uk/intact/complex-ws',
    description: 'Complex Portal 大分子复合物数据库：复合物检索与详情',
    homepage: 'https://www.ebi.ac.uk/complexportal/',
    docsUrl: 'https://www.ebi.ac.uk/complexportal/documentation/',
    endpoints: [
      {
        id: 'search',
        name: '复合物检索',
        method: 'GET',
        path: '/search/{query}',
        description: '按关键词检索复合物，返回 elements 列表',
        params: [
          { name: 'query', required: true, description: '关键词，如 nucleosome', in: 'path' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
          { name: 'first', description: '起始偏移' },
          { name: 'number', description: '返回条数' },
        ],
      },
      {
        id: 'details',
        name: '复合物详情',
        method: 'GET',
        path: '/complex/{ac}',
        description: '按复合物 AC 取成员、功能、属性详情',
        params: [
          { name: 'ac', required: true, description: '复合物编号，如 CPX-915', in: 'path' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
        ],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { query: 'nucleosome', format: 'json', number: '3' },
      expect: { contains: 'elements' },
    },
  },
  {
    id: 'chembl',
    name: 'ChEMBL API',
    category: 'compounds',
    baseUrl: 'https://www.ebi.ac.uk/chembl/api/data',
    description: 'ChEMBL 生物活性数据库：化合物、靶点、活性数据',
    homepage: 'https://www.ebi.ac.uk/chembl/',
    docsUrl: 'https://www.ebi.ac.uk/chembl/api/data/docs',
    endpoints: [
      {
        id: 'molecule',
        name: '化合物详情',
        method: 'GET',
        path: '/molecule/{chemblId}',
        description: '按 ChEMBL ID 取化合物（结构、性质）',
        params: [
          { name: 'chemblId', required: true, description: '如 CHEMBL25（阿司匹林）', in: 'path' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
        ],
      },
      {
        id: 'molecule-search',
        name: '化合物检索',
        method: 'GET',
        path: '/molecule/search',
        description: '按名称关键词检索化合物',
        params: [
          { name: 'q', required: true, description: '关键词，如 aspirin' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
        ],
      },
      {
        id: 'target',
        name: '靶点详情',
        method: 'GET',
        path: '/target/{chemblId}',
        description: '按 ChEMBL ID 取靶点信息',
        params: [
          { name: 'chemblId', required: true, description: '如 CHEMBL240', in: 'path' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
        ],
      },
      {
        id: 'activity',
        name: '活性数据',
        method: 'GET',
        path: '/activity',
        description: '按靶点/化合物过滤生物活性记录（IC50、Ki 等）',
        params: [
          { name: 'target_chembl_id', description: '靶点 ChEMBL ID' },
          { name: 'molecule_chembl_id', description: '化合物 ChEMBL ID' },
          { name: 'limit', description: '返回条数' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
        ],
      },
    ],
    probe: {
      endpoint: 'molecule',
      params: { chemblId: 'CHEMBL25', format: 'json' },
      expect: { contains: 'CHEMBL25' },
    },
  },
  {
    id: 'pubchem',
    name: 'PubChem PUG-REST',
    category: 'compounds',
    baseUrl: 'https://pubchem.ncbi.nlm.nih.gov/rest/pug',
    description: 'PubChem 化合物库：按名称/CID 查结构性质',
    homepage: 'https://pubchem.ncbi.nlm.nih.gov/',
    docsUrl: 'https://pubchemdocs.ncbi.nlm.nih.gov/pug-rest',
    endpoints: [
      {
        id: 'compound-by-name',
        name: '按名称查性质',
        method: 'GET',
        path: '/compound/name/{name}/property/{properties}/JSON',
        description: '按化合物名称取分子式、分子量、SMILES 等性质',
        params: [
          { name: 'name', required: true, description: '名称，如 water / aspirin', in: 'path' },
          { name: 'properties', required: true, description: '逗号分隔，如 MolecularFormula,MolecularWeight,CanonicalSMILES', in: 'path' },
        ],
      },
      {
        id: 'compound-by-cid',
        name: '按 CID 查性质',
        method: 'GET',
        path: '/compound/cid/{cid}/property/{properties}/JSON',
        description: '按 PubChem CID 取性质',
        params: [
          { name: 'cid', required: true, description: 'PubChem CID，如 962', in: 'path' },
          { name: 'properties', required: true, description: '逗号分隔的性质列表', in: 'path' },
        ],
      },
      {
        id: 'cids-by-name',
        name: '名称解析 CID',
        method: 'GET',
        path: '/compound/name/{name}/cids/JSON',
        description: '把化合物名称解析为 CID 列表',
        params: [{ name: 'name', required: true, description: '名称，如 glucose', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'compound-by-name',
      params: { name: 'water', properties: 'MolecularFormula' },
      expect: { contains: 'H2O' },
    },
  },
  {
    id: 'openfda',
    name: 'openFDA (美国 FDA 药品数据)',
    category: 'compounds',
    baseUrl: 'https://api.fda.gov',
    description: '美国 FDA 开放数据：药品说明书（label）与 FAERS 不良事件报告检索',
    homepage: 'https://open.fda.gov',
    docsUrl: 'https://open.fda.gov/apis/',
    authNote: '无 key 限流（约 240 请求/分钟），可申请免费 API key 提速',
    endpoints: [
      {
        id: 'drug-label',
        name: '药品说明书检索',
        method: 'GET',
        path: '/drug/label.json',
        description: 'FDA 药品标签/说明书全文检索',
        params: [
          { name: 'search', description: '检索式，如 openfda.brand_name:aspirin' },
          { name: 'limit', description: '返回条数，默认 1，最大 1000' },
        ],
      },
      {
        id: 'drug-event',
        name: '药品不良事件',
        method: 'GET',
        path: '/drug/event.json',
        description: 'FAERS 不良事件报告检索',
        params: [
          { name: 'search', description: '检索式，如 patient.drug.openfda.brand_name:aspirin' },
          { name: 'limit', description: '返回条数，默认 1，最大 1000' },
        ],
      },
    ],
    probe: {
      endpoint: 'drug-label',
      params: { limit: '1' },
      expect: { contains: 'meta' },
    },
  },
  {
    id: 'pharos',
    name: 'Pharos (TCRD) GraphQL',
    category: 'compounds',
    baseUrl: 'https://pharos-api.ncats.io',
    description: 'NIH IDG Pharos 靶点中心库：靶点-疾病-配体（GraphQL）。替代无稳定公开 API 的 DrugCentral',
    homepage: 'https://pharos.nih.gov/',
    docsUrl: 'https://pharos.nih.gov/api',
    endpoints: [
      {
        id: 'graphql',
        name: 'GraphQL 查询',
        method: 'POST',
        path: '/graphql',
        description: '通用 Pharos GraphQL 查询；示例 { target(q:{sym:"ACE2"}) { sym name tdl } }',
        params: [
          { name: 'query', required: true, description: 'GraphQL 查询字符串', in: 'body' },
          { name: 'variables', description: 'GraphQL 变量对象', in: 'body' },
        ],
      },
      {
        id: 'associated-targets',
        name: '疾病关联靶点',
        method: 'POST',
        path: '/graphql',
        description: '按疾病名查关联靶点；query 示例 query { targets(filter:{associatedDisease:"asthma"}) { targets(top:5) { name sym } } }',
        params: [
          { name: 'query', required: true, description: 'GraphQL 查询字符串', in: 'body' },
          { name: 'variables', description: 'GraphQL 变量对象', in: 'body' },
        ],
      },
    ],
    probe: {
      endpoint: 'graphql',
      params: { query: '{__typename}' },
      expect: { contains: '__typename' },
    },
  },
  {
    id: 'opentargets',
    name: 'Open Targets Platform GraphQL',
    category: 'variants',
    baseUrl: 'https://api.platform.opentargets.org',
    description: 'Open Targets 靶点-疾病关联证据平台（GraphQL）',
    homepage: 'https://platform.opentargets.org/',
    docsUrl: 'https://platform-docs.opentargets.org/data-access/graphql-api',
    endpoints: [
      {
        id: 'graphql',
        name: 'GraphQL 查询',
        method: 'POST',
        path: '/api/v4/graphql',
        description: '通用查询；示例 { search(queryString:"asthma", entityNames:["disease"]) { hits { id name entity } } }',
        params: [
          { name: 'query', required: true, description: 'GraphQL 查询字符串', in: 'body' },
          { name: 'variables', description: 'GraphQL 变量对象', in: 'body' },
        ],
      },
      {
        id: 'target-disease-association',
        name: '靶点-疾病关联',
        method: 'POST',
        path: '/api/v4/graphql',
        description: '示例 query { target(ensemblId:"ENSG00000157764") { approvedSymbol associatedDiseases(page:{index:0,size:5}) { rows { disease { name } score } } } }',
        params: [
          { name: 'query', required: true, description: 'GraphQL 查询字符串', in: 'body' },
          { name: 'variables', description: 'GraphQL 变量对象', in: 'body' },
        ],
      },
    ],
    probe: {
      endpoint: 'graphql',
      params: { query: '{ meta { name } }' },
      expect: { contains: 'Open Targets' },
    },
  },
  {
    id: 'cbioportal',
    name: 'cBioPortal 癌症基因组',
    category: 'variants',
    baseUrl: 'https://www.cbioportal.org',
    description: 'cBioPortal 癌症基因组学公共数据库：研究、样本、突变与拷贝数数据（替代 gnomAD——后者无 key 时限流频繁）',
    homepage: 'https://www.cbioportal.org/',
    docsUrl: 'https://www.cbioportal.org/api/swagger-ui.html',
    endpoints: [
      {
        id: 'studies',
        name: '研究列表',
        method: 'GET',
        path: '/api/studies',
        description: '癌症基因组研究列表（pageSize 控制数量）',
        params: [
          { name: 'pageSize', description: '每页数量', in: 'query' },
          { name: 'projection', description: 'SUMMARY 或 DETAILED', in: 'query' },
        ],
      },
      {
        id: 'study-detail',
        name: '研究详情',
        method: 'GET',
        path: '/api/studies/{studyId}',
        description: '按 studyId 取研究详情',
        params: [
          { name: 'studyId', required: true, description: '研究 id', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'studies',
      params: { pageSize: '1', projection: 'SUMMARY' },
      expect: { contains: 'studyId' },
    },
  },
  {
    id: 'clinicaltables',
    name: 'NLM Clinical Tables（临床术语）',
    category: 'variants',
    baseUrl: 'https://clinicaltables.nlm.nih.gov',
    description: '美国国立医学图书馆临床术语服务：疾病/症状与 ICD-10-CM 编码检索（变异临床解读辅助）',
    homepage: 'https://clinicaltables.nlm.nih.gov/',
    docsUrl: 'https://clinicaltables.nlm.nih.gov/apidoc/conditions/v3/doc.html',
    authNote: '响应为 JSON 数组 [总数, 编号数组, 额外字段, 显示名数组]；替代从本网络不可达的 Ensembl VEP',
    endpoints: [
      {
        id: 'conditions-search',
        name: '疾病/症状检索',
        method: 'GET',
        path: '/api/conditions/v3/search',
        description: '临床疾病与症状术语检索（NLM）',
        params: [
          { name: 'terms', required: true, description: '关键词，如 diabetes' },
          { name: 'maxList', description: '返回条数上限' },
        ],
      },
      {
        id: 'icd10',
        name: 'ICD-10 编码检索',
        method: 'GET',
        path: '/api/icd10cm/v3/search',
        description: 'ICD-10-CM 编码检索',
        params: [
          { name: 'terms', required: true, description: '关键词或编码前缀，如 E11' },
          { name: 'maxList', description: '返回条数上限' },
          { name: 'sf', description: '附加返回字段，如 code,name' },
        ],
      },
    ],
    probe: {
      endpoint: 'conditions-search',
      params: { terms: 'diabetes', maxList: '1' },
      expect: { contains: 'Diabetes' },
    },
  },
  {
    id: 'clingen-allele',
    name: 'ClinGen Allele Registry',
    category: 'variants',
    baseUrl: 'https://reg.clinicalgenome.org',
    description: 'ClinGen 等位基因注册表：HGVS 解析为规范 CA 编号',
    homepage: 'https://reg.clinicalgenome.org/',
    docsUrl: 'https://reg.clinicalgenome.org/',
    authNote: '查询公开无需账号；注册新等位基因（写入）需要 ClinGen 账号',
    endpoints: [
      {
        id: 'allele-by-hgvs',
        name: 'HGVS 解析',
        method: 'GET',
        path: '/allele',
        description: '按 HGVS 记法查已注册等位基因（CA ID、坐标）',
        params: [{ name: 'hgvs', required: true, description: '如 NC_000007.14:g.140753336A>T' }],
      },
      {
        id: 'allele-by-id',
        name: '按 CA 编号查询',
        method: 'GET',
        path: '/allele/{id}',
        description: '按 ClinGen Allele 编号取等位基因记录',
        params: [{ name: 'id', required: true, description: 'CA 编号，如 CA512558', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'allele-by-hgvs',
      params: { hgvs: 'NC_000007.14:g.140753336A>T' },
      expect: { contains: '140753336' },
    },
  },
  {
    id: 'myvariant',
    name: 'MyVariant.info',
    category: 'variants',
    baseUrl: 'https://myvariant.info/v1',
    description: '变异注释聚合（ClinVar、dbNSFP、gnomAD 等）',
    homepage: 'https://myvariant.info/',
    docsUrl: 'https://docs.myvariant.info/',
    endpoints: [
      {
        id: 'variant',
        name: '变异详情',
        method: 'GET',
        path: '/variant/{id}',
        description: '按 rsID 或 HGVS（如 chr6:g.26093141G>A）取聚合注释',
        params: [
          { name: 'id', required: true, description: 'rsID 或 HGVS', in: 'path' },
          { name: 'fields', description: '返回字段过滤，如 clinvar,dbsnp' },
        ],
      },
      {
        id: 'query',
        name: '变异检索',
        method: 'GET',
        path: '/query',
        description: '按查询语法检索变异，如 q=clinvar.rcv.clinical_significance:pathogenic',
        params: [
          { name: 'q', required: true, description: '查询式，如 rs58991260' },
          { name: 'size', description: '返回条数，默认 10' },
          { name: 'fields', description: '返回字段过滤' },
        ],
      },
    ],
    probe: {
      endpoint: 'query',
      params: { q: 'rs58991260', size: '1' },
      expect: { contains: 'rs58991260' },
    },
  },
  {
    id: 'mygene',
    name: 'MyGene.info',
    category: 'genes-genomes',
    baseUrl: 'https://mygene.info/v3',
    description: '基因注释聚合：ID 转换、基因基本信息一站式查询',
    homepage: 'https://mygene.info/',
    docsUrl: 'https://docs.mygene.info/',
    endpoints: [
      {
        id: 'gene',
        name: '基因详情',
        method: 'GET',
        path: '/gene/{id}',
        description: '按 Entrez/Ensembl ID 取基因聚合注释',
        params: [
          { name: 'id', required: true, description: 'Entrez 或 Ensembl ID，如 1017', in: 'path' },
          { name: 'fields', description: '字段过滤，如 symbol,name,summary' },
        ],
      },
      {
        id: 'query',
        name: '基因检索',
        method: 'GET',
        path: '/query',
        description: '按查询语法检索基因，如 q=symbol:CDK2 AND species:human',
        params: [
          { name: 'q', required: true, description: '查询式' },
          { name: 'size', description: '返回条数，默认 10' },
          { name: 'species', description: '物种过滤，如 human' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { id: '1017' },
      expect: { contains: 'CDK2' },
    },
  },
  {
    id: 'ucsc',
    name: 'UCSC Genome Browser API',
    category: 'genes-genomes',
    baseUrl: 'https://api.genome.ucsc.edu',
    description: 'UCSC 基因组浏览器数据：参考序列与轨道数据',
    homepage: 'https://genome.ucsc.edu/',
    docsUrl: 'https://genome.ucsc.edu/goldenPath/help/api.html',
    endpoints: [
      {
        id: 'sequence',
        name: '取参考序列',
        method: 'GET',
        path: '/getData/sequence',
        description: '取某组装指定区段的参考基因组序列',
        params: [
          { name: 'genome', required: true, description: '组装，如 hg38' },
          { name: 'chrom', required: true, description: '染色体，如 chr7' },
          { name: 'start', description: '0 基起点' },
          { name: 'end', description: '终点' },
        ],
      },
      {
        id: 'track',
        name: '轨道数据',
        method: 'GET',
        path: '/getData/track',
        description: '取某轨道（如 knownCanonical、rmsk）指定区段的数据',
        params: [
          { name: 'genome', required: true, description: '组装，如 hg38' },
          { name: 'track', required: true, description: '轨道名，如 knownCanonical' },
          { name: 'chrom', description: '染色体，如 chr1' },
          { name: 'start', description: '0 基起点' },
          { name: 'end', description: '终点' },
        ],
      },
      {
        id: 'genomes',
        name: '组装列表',
        method: 'GET',
        path: '/list/ucscGenomes',
        description: '列出 UCSC 支持的全部基因组组装',
      },
    ],
    probe: {
      endpoint: 'genomes',
      expect: { contains: 'hg38' },
    },
  },
  {
    id: 'jaspar',
    name: 'JASPAR API',
    category: 'genes-genomes',
    baseUrl: 'https://jaspar.genereg.net/api/v1',
    description: 'JASPAR 转录因子结合 motif 库：矩阵检索与获取',
    homepage: 'https://jaspar.genereg.net/',
    docsUrl: 'https://jaspar.genereg.net/docs/api/',
    endpoints: [
      {
        id: 'matrix',
        name: '矩阵详情',
        method: 'GET',
        path: '/matrix/{id}/',
        description: '按矩阵 ID 取 motif（PFM、类别、物种）',
        params: [{ name: 'id', required: true, description: '矩阵 ID，如 MA0001.1', in: 'path' }],
      },
      {
        id: 'matrix-search',
        name: '矩阵检索',
        method: 'GET',
        path: '/matrix/',
        description: '按关键词/集合检索 motif 矩阵',
        params: [
          { name: 'search', description: '关键词，如 AGL3' },
          { name: 'collection', description: '集合，如 CORE' },
          { name: 'page_size', description: '每页条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'matrix',
      params: { id: 'MA0001.1' },
      expect: { contains: 'MA0001' },
    },
  },
  {
    id: 'oma',
    name: 'OMA 直系同源数据库',
    category: 'genes-genomes',
    baseUrl: 'https://omabrowser.org',
    description: 'OMA 全基因组直系同源推断：蛋白条目、同源组、物种基因组（转录因子 motif 库 HOCOMOCO 的 /api/v1 已下线，转录调控查询改用 JASPAR(#27)）',
    homepage: 'https://omabrowser.org/oma/home/',
    docsUrl: 'https://omabrowser.org/api/docs',
    endpoints: [
      {
        id: 'protein',
        name: '蛋白条目',
        method: 'GET',
        path: '/api/protein/{id}/',
        description: '按 canonical id 查蛋白与同源信息',
        params: [{ name: 'id', required: true, description: '如 P53_HUMAN', in: 'path' }],
      },
      {
        id: 'genome',
        name: '物种基因组',
        method: 'GET',
        path: '/api/genome/{id}/',
        description: '物种信息与基因列表',
        params: [{ name: 'id', required: true, description: '物种代码，如 HUMAN', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'protein',
      params: { id: 'P53_HUMAN' },
      expect: { contains: 'omaid' },
    },
  },
  {
    id: 'hgnc',
    name: 'HGNC REST',
    category: 'genes-genomes',
    baseUrl: 'https://rest.genenames.org',
    description: 'HGNC 人类基因命名委员会：基因符号/别名规范查询',
    homepage: 'https://www.genenames.org/',
    docsUrl: 'https://www.genenames.org/help/rest/',
    endpoints: [
      {
        id: 'fetch-symbol',
        name: '按符号查询',
        method: 'GET',
        path: '/fetch/symbol/{symbol}',
        description: '按官方基因符号取命名记录',
        params: [{ name: 'symbol', required: true, description: '如 BRCA1', in: 'path' }],
      },
      {
        id: 'fetch-id',
        name: '按 HGNC ID 查询',
        method: 'GET',
        path: '/fetch/hgnc_id/{id}',
        description: '按 HGNC ID 取命名记录',
        params: [{ name: 'id', required: true, description: '如 HGNC:1100', in: 'path' }],
      },
      {
        id: 'search',
        name: '检索',
        method: 'GET',
        path: '/search/{query}',
        description: '按关键词检索命名记录，如 BRCA',
        params: [{ name: 'query', required: true, description: '关键词', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'fetch-symbol',
      params: { symbol: 'BRCA1' },
      expect: { contains: 'BRCA1' },
    },
  },
  {
    id: 'mgi',
    name: 'MGI（经 AGR 查询）',
    category: 'taxonomy',
    baseUrl: 'https://www.alliancegenome.org/api',
    description: '小鼠基因组信息（MGI）：经 Alliance of Genome Resources 聚合 API 查询基因/表型/疾病模型',
    homepage: 'https://www.informatics.jax.org/',
    docsUrl: 'https://www.alliancegenome.org/swagger-ui/',
    authNote: 'MGI 官网无稳定公开 JSON API，本条目经 AGR(alliancegenome.org) 查询，gene id 形如 MGI:98834',
    endpoints: [
      {
        id: 'gene',
        name: '小鼠基因详情',
        method: 'GET',
        path: '/gene/{id}',
        description: '按 MGI ID 取基因信息（符号、物种、位置、交叉引用）',
        params: [{ name: 'id', required: true, description: '如 MGI:98834', in: 'path' }],
      },
      {
        id: 'gene-phenotypes',
        name: '基因表型',
        method: 'GET',
        path: '/gene/{id}/phenotypes',
        description: '取小鼠基因的表型注释（分页）',
        params: [
          { name: 'id', required: true, description: 'MGI ID', in: 'path' },
          { name: 'limit', description: '每页条数' },
          { name: 'page', description: '页码，从 1 开始' },
        ],
      },
      {
        id: 'search',
        name: '基因检索',
        method: 'GET',
        path: '/search_autocomplete',
        description: '按关键词自动补全检索基因',
        params: [
          { name: 'q', required: true, description: '关键词，如 pax6' },
          { name: 'category', description: '传 gene 限定基因' },
          { name: 'limit', description: '返回条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { id: 'MGI:98834' },
      expect: { contains: 'primaryExternalId' },
    },
  },
  {
    id: 'flybase',
    name: 'FlyBase（经 AGR 查询）',
    category: 'taxonomy',
    baseUrl: 'https://www.alliancegenome.org/api',
    description: '果蝇数据库（FlyBase）：经 Alliance of Genome Resources 聚合 API 查询',
    homepage: 'https://flybase.org/',
    docsUrl: 'https://www.alliancegenome.org/swagger-ui/',
    authNote: 'FlyBase 无公开 JSON 查询 API，本条目经 AGR 查询，gene id 形如 FB:FBgn0003996',
    endpoints: [
      {
        id: 'gene',
        name: '果蝇基因详情',
        method: 'GET',
        path: '/gene/{id}',
        description: '按 FBgn ID 取基因信息',
        params: [{ name: 'id', required: true, description: '如 FB:FBgn0003996', in: 'path' }],
      },
      {
        id: 'gene-alleles',
        name: '基因等位',
        method: 'GET',
        path: '/gene/{id}/alleles',
        description: '取果蝇基因的等位基因/变异列表（分页）',
        params: [
          { name: 'id', required: true, description: 'FBgn ID', in: 'path' },
          { name: 'limit', description: '每页条数' },
          { name: 'page', description: '页码，从 1 开始' },
        ],
      },
      {
        id: 'search',
        name: '基因检索',
        method: 'GET',
        path: '/search_autocomplete',
        description: '按关键词自动补全检索基因',
        params: [
          { name: 'q', required: true, description: '关键词，如 notch' },
          { name: 'category', description: '传 gene 限定基因' },
          { name: 'limit', description: '返回条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { id: 'FB:FBgn0003996' },
      expect: { contains: 'primaryExternalId' },
    },
  },
  {
    id: 'wormbase',
    name: 'WormBase（经 AGR 查询）',
    category: 'taxonomy',
    baseUrl: 'https://www.alliancegenome.org/api',
    description: '线虫数据库（WormBase）：经 Alliance of Genome Resources 聚合 API 查询',
    homepage: 'https://wormbase.org/',
    docsUrl: 'https://www.alliancegenome.org/swagger-ui/',
    authNote: 'WormBase REST 已不稳定，本条目经 AGR 查询，gene id 形如 WB:WBGene00000001',
    endpoints: [
      {
        id: 'gene',
        name: '线虫基因详情',
        method: 'GET',
        path: '/gene/{id}',
        description: '按 WBGene ID 取基因信息',
        params: [{ name: 'id', required: true, description: '如 WB:WBGene00000001', in: 'path' }],
      },
      {
        id: 'gene-orthologs',
        name: '直系同源',
        method: 'GET',
        path: '/gene/{id}/orthologs',
        description: '取线虫基因的跨物种直系同源（分页）',
        params: [
          { name: 'id', required: true, description: 'WBGene ID', in: 'path' },
          { name: 'limit', description: '每页条数' },
          { name: 'page', description: '页码，从 1 开始' },
        ],
      },
      {
        id: 'search',
        name: '基因检索',
        method: 'GET',
        path: '/search_autocomplete',
        description: '按关键词自动补全检索基因',
        params: [
          { name: 'q', required: true, description: '关键词，如 unc-13' },
          { name: 'category', description: '传 gene 限定基因' },
          { name: 'limit', description: '返回条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { id: 'WB:WBGene00000001' },
      expect: { contains: 'primaryExternalId' },
    },
  },
  {
    id: 'sgd',
    name: 'SGD（经 AGR 查询）',
    category: 'taxonomy',
    baseUrl: 'https://www.alliancegenome.org/api',
    description: '酵母基因组数据库（SGD）：经 Alliance of Genome Resources 聚合 API 查询',
    homepage: 'https://www.yeastgenome.org/',
    docsUrl: 'https://www.alliancegenome.org/swagger-ui/',
    authNote: 'SGD webservice 已不稳定，本条目经 AGR 查询，gene id 形如 SGD:S000003424',
    endpoints: [
      {
        id: 'gene',
        name: '酵母基因详情',
        method: 'GET',
        path: '/gene/{id}',
        description: '按 SGD ID 取基因信息',
        params: [{ name: 'id', required: true, description: '如 SGD:S000003424', in: 'path' }],
      },
      {
        id: 'gene-expression',
        name: '表达摘要',
        method: 'GET',
        path: '/gene/{id}/expression-summary',
        description: '取酵母基因的表达注释摘要（按组织/条件分组）',
        params: [{ name: 'id', required: true, description: 'SGD ID', in: 'path' }],
      },
      {
        id: 'search',
        name: '基因检索',
        method: 'GET',
        path: '/search_autocomplete',
        description: '按关键词自动补全检索基因',
        params: [
          { name: 'q', required: true, description: '关键词，如 act1' },
          { name: 'category', description: '传 gene 限定基因' },
          { name: 'limit', description: '返回条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { id: 'SGD:S000003424' },
      expect: { contains: 'primaryExternalId' },
    },
  },
  {
    id: 'tair',
    name: 'TAIR（经 Gramene 查询）',
    category: 'plants',
    baseUrl: 'https://data.gramene.org/v69',
    description: '拟南芥数据（TAIR）：经 Gramene REST 查询 Arabidopsis thaliana 基因与注释',
    homepage: 'https://www.arabidopsis.org/',
    docsUrl: 'https://www.gramene.org/web-services',
    authNote: 'TAIR 无公开 JSON API；经 Gramene 查询（fq=taxonomy__ancestors:3702 限定拟南芥）',
    endpoints: [
      {
        id: 'search-arabidopsis',
        name: '拟南芥基因检索',
        method: 'GET',
        path: '/search',
        description: 'Solr 检索拟南芥基因（固定带 fq=taxonomy__ancestors:3702）',
        params: [
          { name: 'q', required: true, description: '关键词，如 flowering' },
          { name: 'fq', description: '过滤式，建议 taxonomy__ancestors:3702' },
          { name: 'rows', description: '返回条数' },
        ],
      },
      {
        id: 'genes',
        name: '基因文档',
        method: 'GET',
        path: '/genes',
        description: '按 ID 列表或关键词取拟南芥基因注释文档',
        params: [
          { name: 'idList', description: '逗号分隔的基因 ID，如 AT1G01010' },
          { name: 'q', description: '文本检索' },
        ],
      },
    ],
    probe: {
      endpoint: 'search-arabidopsis',
      params: { q: 'flowering', fq: 'taxonomy__ancestors:3702', rows: '1' },
      expect: { contains: 'numFound' },
    },
  },
  {
    id: 'gramene',
    name: 'Gramene REST',
    category: 'plants',
    baseUrl: 'https://data.gramene.org/v69',
    description: 'Gramene 植物比较基因组：30+ 物种基因检索、同源、表达',
    homepage: 'https://www.gramene.org/',
    docsUrl: 'https://www.gramene.org/web-services',
    endpoints: [
      {
        id: 'search',
        name: '基因检索（Solr）',
        method: 'GET',
        path: '/search',
        description: '按关键词/Solr 查询式检索植物基因',
        params: [
          { name: 'q', required: true, description: '查询式，如 id:SORBI_3006G095600 或关键词' },
          { name: 'fq', description: '过滤式，如 taxonomy__ancestors:4558' },
          { name: 'rows', description: '返回条数' },
        ],
      },
      {
        id: 'suggest',
        name: '概念联想',
        method: 'GET',
        path: '/suggest',
        description: '自由文本概念联想（基因名、通路、本体、性状）→ 检索入口',
        params: [{ name: 'q', required: true, description: '关键词，如 flowering' }],
      },
      {
        id: 'genes',
        name: '基因文档',
        method: 'GET',
        path: '/genes',
        description: 'Mongo 基因集合：按 ID 列表或字段等值过滤取文档',
        params: [
          { name: 'idList', description: '逗号分隔的基因 ID' },
          { name: 'q', description: '文本检索' },
        ],
      },
    ],
    probe: {
      endpoint: 'suggest',
      params: { q: 'flowering' },
      expect: { contains: 'grouped' },
    },
  },
  {
    id: 'phytozome',
    name: 'Phytozome/JGI',
    category: 'plants',
    baseUrl: 'https://phytozome-next.jgi.doe.gov',
    description: 'JGI Phytozome 植物比较基因组：基因/物种公开搜索',
    homepage: 'https://phytozome-next.jgi.doe.gov/',
    docsUrl: 'https://phytozome-next.jgi.doe.gov/',
    authNote: 'Phytozome-next 搜索 API 公开可用；基因组数据下载需 JGI 注册登录（表单认证）。Ensembl Plants 主站从本网络不可达，本服务直接走 JGI',
    endpoints: [
      {
        id: 'search',
        name: '关键词搜索',
        method: 'GET',
        path: '/api/search',
        description: '按关键词搜索植物基因/物种/注释（Phytozome-next 公开搜索 API）',
        params: [{ name: 'q', required: true, description: '关键词，如 phytochrome' }],
      },
      {
        id: 'search-organism',
        name: '物种组合搜索',
        method: 'GET',
        path: '/api/search',
        description: '按物种名+关键词组合搜索（同一接口，query 中带物种名）',
        params: [{ name: 'q', required: true, description: '如 Oryza sativa phytochrome' }],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { q: 'phytochrome' },
      expect: {},
    },
  },
  {
    id: 'hpa',
    name: 'Human Protein Atlas API',
    category: 'expression',
    baseUrl: 'https://www.proteinatlas.org',
    description: '人类蛋白图谱：组织表达、亚细胞定位、病理图谱',
    homepage: 'https://www.proteinatlas.org/',
    docsUrl: 'https://www.proteinatlas.org/about/help/dataaccess',
    endpoints: [
      {
        id: 'gene',
        name: '单基因条目',
        method: 'GET',
        path: '/{ensemblId}.json',
        description: '按 Ensembl ID 取该基因全部 HPA 数据（组织 RNA/蛋白表达、定位）',
        params: [{ name: 'ensemblId', required: true, description: '如 ENSG00000012048（BRCA1）', in: 'path' }],
      },
      {
        id: 'search-download',
        name: '检索下载',
        method: 'GET',
        path: '/api/search_download.php',
        description: '按关键词检索并以 JSON 批量取 HPA 数据列',
        params: [
          { name: 'search', required: true, description: '关键词，如 P53' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
          { name: 'columns', description: '逗号分隔的列，如 g,gs,eg,up（见 dataaccess 文档）' },
        ],
      },
    ],
    probe: {
      endpoint: 'gene',
      params: { ensemblId: 'ENSG00000012048' },
      expect: { contains: 'BRCA1' },
    },
  },
  {
    id: 'expressionatlas',
    name: 'Expression Atlas API',
    category: 'expression',
    baseUrl: 'https://www.ebi.ac.uk/gxa',
    description: 'EBI 表达图谱：基线/差异表达实验目录与元数据',
    homepage: 'https://www.ebi.ac.uk/gxa/',
    docsUrl: 'https://www.ebi.ac.uk/gxa/help/',
    endpoints: [
      {
        id: 'experiments',
        name: '实验目录',
        method: 'GET',
        path: '/json/experiments',
        description: '列出全部表达实验（可按物种/类型自行过滤）',
      },
      {
        id: 'experiment',
        name: '实验详情',
        method: 'GET',
        path: '/json/experiments/{accession}',
        description: '按登录号取实验设计、对照与 assay 元数据',
        params: [{ name: 'accession', required: true, description: '如 E-MTAB-513', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'experiment',
      params: { accession: 'E-MTAB-513' },
      expect: { contains: 'E-MTAB-513' },
    },
  },
  {
    id: 'sc-expressionatlas',
    name: 'Single Cell Expression Atlas',
    category: 'expression',
    baseUrl: 'https://www.ebi.ac.uk/gxa/sc/json',
    description: 'EBI 单细胞表达图谱：单细胞实验目录、按基因找实验、marker 基因',
    homepage: 'https://www.ebi.ac.uk/gxa/sc/',
    docsUrl: 'https://www.ebi.ac.uk/gxa/sc/help/',
    endpoints: [
      {
        id: 'experiments',
        name: '单细胞实验目录',
        method: 'GET',
        path: '/experiments',
        description: '列出全部单细胞 RNA-seq 实验（物种、细胞数、技术）',
      },
      {
        id: 'search',
        name: '按基因找实验',
        method: 'GET',
        path: '/search',
        description: '查某基因在哪些单细胞实验中表达',
        params: [
          { name: 'symbol', description: '基因符号，如 TP53（与 ensgene 二选一）' },
          { name: 'ensgene', description: 'Ensembl 基因 ID，如 ENSG00000141510' },
          { name: 'species', description: '物种过滤' },
        ],
      },
      {
        id: 'marker-genes',
        name: 'marker 基因',
        method: 'GET',
        path: '/experiments/{accession}/marker-genes/clusters',
        description: '取某实验在指定聚类分辨率 k 下的各簇 marker 基因',
        params: [
          { name: 'accession', required: true, description: '实验登录号，如 E-MTAB-5061', in: 'path' },
          { name: 'k', required: true, description: '聚类分辨率（簇数），如 8' },
        ],
      },
    ],
    probe: {
      endpoint: 'experiments',
      expect: { contains: 'experimentAccession' },
    },
  },
  {
    id: 'pride',
    name: 'PRIDE Archive API',
    category: 'proteins',
    baseUrl: 'https://www.ebi.ac.uk/pride/ws/archive/v2',
    description: 'PRIDE 蛋白质组学数据存档：项目检索与文件列表',
    homepage: 'https://www.ebi.ac.uk/pride/',
    docsUrl: 'https://www.ebi.ac.uk/pride/ws/archive/v2/swagger-ui/index.html',
    endpoints: [
      {
        id: 'project',
        name: '项目详情',
        method: 'GET',
        path: '/projects/{accession}',
        description: '按 PXD 登录号取项目元数据',
        params: [{ name: 'accession', required: true, description: '如 PXD000001', in: 'path' }],
      },
      {
        id: 'search-projects',
        name: '项目检索',
        method: 'GET',
        path: '/search/projects',
        description: '按关键词检索蛋白质组学项目',
        params: [
          { name: 'keyword', required: true, description: '关键词，如 phosphoproteomics' },
          { name: 'pageSize', description: '每页条数' },
          { name: 'page', description: '页码' },
        ],
      },
      {
        id: 'files',
        name: '项目文件',
        method: 'GET',
        path: '/files',
        description: '列某项目的全部数据文件',
        params: [
          { name: 'projectAccession', required: true, description: 'PXD 登录号' },
          { name: 'page', description: '页码' },
          { name: 'pageSize', description: '每页条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'project',
      params: { accession: 'PXD000001' },
      expect: { contains: 'PXD000001' },
    },
  },
  {
    id: 'metabolights',
    name: 'MetaboLights WS',
    category: 'compounds',
    baseUrl: 'https://www.ebi.ac.uk/metabolights/ws',
    description: 'MetaboLights 代谢组学数据存档：研究与代谢物',
    homepage: 'https://www.ebi.ac.uk/metabolights/',
    docsUrl: 'https://www.ebi.ac.uk/metabolights/help',
    endpoints: [
      {
        id: 'studies',
        name: '研究列表',
        method: 'GET',
        path: '/studies',
        description: '列出全部公开研究登录号（JSON 数组）',
      },
      {
        id: 'study',
        name: '研究详情',
        method: 'GET',
        path: '/studies/{id}',
        description: '按 MTBLS 登录号取研究元数据',
        params: [{ name: 'id', required: true, description: '如 MTBLS1', in: 'path' }],
      },
      {
        id: 'study-files',
        name: '研究文件',
        method: 'GET',
        path: '/studies/{id}/files',
        description: '列某研究的数据文件',
        params: [{ name: 'id', required: true, description: 'MTBLS 登录号', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'study',
      params: { id: 'MTBLS1' },
      expect: { contains: 'MTBLS1' },
    },
  },
  {
    id: 'chebi',
    name: 'ChEBI 2.0 REST',
    category: 'compounds',
    baseUrl: 'https://www.ebi.ac.uk/chebi/backend/api/public',
    description: 'ChEBI 生物活性小分子词典与本体（2025 新 REST，替代旧 SOAP）',
    homepage: 'https://www.ebi.ac.uk/chebi/',
    docsUrl: 'https://www.ebi.ac.uk/chebi/backend/api/docs/',
    authNote: 'ChEBI 2.0 新 REST API（2025 年替换旧 SOAP webservice），无需认证',
    endpoints: [
      {
        id: 'compound',
        name: '化合物详情',
        method: 'GET',
        path: '/compound/{chebiId}/',
        description: '按 ChEBI ID 取完整条目（名称、定义、式、质量、SMILES）',
        params: [{ name: 'chebiId', required: true, description: '如 CHEBI:15377（水）', in: 'path' }],
      },
      {
        id: 'search',
        name: '全文检索',
        method: 'GET',
        path: '/es_search/',
        description: '按关键词全文检索 ChEBI 条目',
        params: [{ name: 'term', required: true, description: '关键词，如 glucose' }],
      },
      {
        id: 'compounds',
        name: '条目列表',
        method: 'GET',
        path: '/compounds/',
        description: '分页列出 ChEBI 条目',
      },
    ],
    probe: {
      endpoint: 'compound',
      params: { chebiId: 'CHEBI:15377' },
      expect: { contains: '15377' },
    },
  },
  {
    id: 'rhea',
    name: 'Rhea REST',
    category: 'pathways',
    baseUrl: 'https://www.rhea-db.org',
    description: 'Rhea 生化反应数据库：反应检索与条目获取',
    homepage: 'https://www.rhea-db.org/',
    docsUrl: 'https://www.rhea-db.org/help/rest-api',
    authNote: '官方响应为 TSV/RD 文本（无 JSON）；建议程序 UA 中带联系邮箱',
    endpoints: [
      {
        id: 'search',
        name: '反应检索',
        method: 'GET',
        path: '/rhea/',
        description: '按查询式检索反应，TSV 返回所选列',
        params: [
          { name: 'query', required: true, description: '查询式，如 ec:1.1.1.1 或 uniprot:*（空串取全部）' },
          { name: 'columns', description: '逗号分隔列，如 rhea-id,equation,chebi-id' },
          { name: 'format', description: '传 tsv' },
          { name: 'limit', description: '返回条数上限' },
        ],
      },
      {
        id: 'entry',
        name: '反应条目',
        method: 'GET',
        path: '/rhea/{id}.rd',
        description: '按反应编号取 RD 格式条目（无 RHEA: 前缀）',
        params: [{ name: 'id', required: true, description: '反应编号，如 10661', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { query: 'uniprot:*', columns: 'rhea-id,equation', format: 'tsv', limit: '5' },
      expect: { contains: 'RHEA' },
    },
  },
  {
    id: 'mychem',
    name: 'MyChem.info 化合物注释',
    category: 'compounds',
    baseUrl: 'https://mychem.info',
    description: 'MyChem.info 化合物聚合注释（DrugBank/ChEMBL/PubChem/DrugCentral 等；BioCyc/MetaCyc 从本网络不可达，代谢化合物查询走此）',
    homepage: 'https://mychem.info/',
    docsUrl: 'https://docs.mychem.info/',
    endpoints: [
      {
        id: 'chem',
        name: '化合物详情',
        method: 'GET',
        path: '/v1/chem/{id}',
        description: '按 DrugBank/ChEMBL/PubChem id 查化合物聚合注释',
        params: [
          { name: 'id', required: true, description: '如 DB00563 / CHEMBL25 / 2244', in: 'path' },
          { name: 'fields', description: '字段过滤，如 drugbank,chebi,pubchem' },
        ],
      },
      {
        id: 'query',
        name: '化合物检索',
        method: 'GET',
        path: '/v1/query',
        description: '字段化检索（q 参数 Lucene 语法）',
        params: [
          { name: 'q', required: true, description: '查询式，如 drugbank.name:aspirin' },
          { name: 'size', description: '返回条数，默认 10' },
          { name: 'fields', description: '字段过滤' },
        ],
      },
    ],
    probe: {
      endpoint: 'chem',
      params: { id: 'DB00563' },
      expect: { contains: '_id' },
    },
  },
  {
    id: 'rnacentral',
    name: 'RNAcentral API',
    category: 'genes-genomes',
    baseUrl: 'https://rnacentral.org/api/v1',
    description: 'RNAcentral 非编码 RNA 序列聚合库',
    homepage: 'https://rnacentral.org/',
    docsUrl: 'https://rnacentral.org/api',
    endpoints: [
      {
        id: 'rna',
        name: 'RNA 条目',
        method: 'GET',
        path: '/rna/{id}/',
        description: '按 URS ID 取 ncRNA 条目（序列、长度、物种）',
        params: [{ name: 'id', required: true, description: '如 URS0000000001', in: 'path' }],
      },
      {
        id: 'rna-xrefs',
        name: 'RNA 交叉引用',
        method: 'GET',
        path: '/rna/{id}/xrefs/',
        description: '取某 URS 的全部外部数据库交叉引用',
        params: [{ name: 'id', required: true, description: 'URS ID', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'rna',
      params: { id: 'URS0000000001' },
      expect: { contains: 'URS0000000001' },
    },
  },
  {
    id: 'mirbase',
    name: 'miRBase',
    category: 'genes-genomes',
    baseUrl: 'https://www.mirbase.org',
    description: 'miRBase microRNA 序列与注释库（条目页 HTML）',
    homepage: 'https://www.mirbase.org/',
    docsUrl: 'https://www.mirbase.org/',
    authNote: 'miRBase 无公开 JSON API，端点返回 HTML 条目页供解析；站点偶有 503 维护窗口，健康检测失败时可先用 rnacentral 服务替代检索 miRNA；批量数据走官方 FTP',
    endpoints: [
      {
        id: 'hairpin',
        name: '前体条目',
        method: 'GET',
        path: '/hairpin/{acc}',
        description: '按前体登录号取 miRNA 条目页，如 MI0000060（hsa-let-7a-1）',
        params: [{ name: 'acc', required: true, description: 'MI 编号，如 MI0000060', in: 'path' }],
      },
      {
        id: 'mature',
        name: '成熟体条目',
        method: 'GET',
        path: '/mature/{acc}',
        description: '按成熟体登录号取条目页，如 MIMAT0000062（hsa-let-7a-5p）',
        params: [{ name: 'acc', required: true, description: 'MIMAT 编号', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'hairpin',
      params: { acc: 'MI0000060' },
      expect: { contains: 'let-7' },
    },
  },
  {
    id: 'europepmc',
    name: 'Europe PMC REST',
    category: 'literature',
    baseUrl: 'https://www.ebi.ac.uk/europepmc/webservices/rest',
    description: 'Europe PMC 文献库：检索、全文 XML、引用关系',
    homepage: 'https://europepmc.org/',
    docsUrl: 'https://europepmc.org/docs/EBI_Europe_PMC_Web_Service_Reference.pdf',
    endpoints: [
      {
        id: 'search',
        name: '文献检索',
        method: 'GET',
        path: '/search',
        description: '按查询语法检索文献，如 query=COVID-19 AND OPEN_ACCESS:y',
        params: [
          { name: 'query', required: true, description: '查询式' },
          { name: 'format', description: '传 json 获取 JSON 响应' },
          { name: 'pageSize', description: '每页条数，默认 25' },
        ],
      },
      {
        id: 'fulltext',
        name: '全文 XML',
        method: 'GET',
        path: '/{pmcid}/fullTextXML',
        description: '按 PMCID 取开放获取全文 JATS XML',
        params: [{ name: 'pmcid', required: true, description: '如 PMC3257301', in: 'path' }],
      },
      {
        id: 'citations',
        name: '引用列表',
        method: 'GET',
        path: '/{source}/{id}/citations/{page}/{pageSize}/{format}',
        description: '取某文献的被引列表',
        params: [
          { name: 'source', required: true, description: '来源库，如 MED', in: 'path' },
          { name: 'id', required: true, description: '文献 ID（PMID）', in: 'path' },
          { name: 'page', required: true, description: '页码，从 1 开始', in: 'path' },
          { name: 'pageSize', required: true, description: '每页条数，如 25', in: 'path' },
          { name: 'format', required: true, description: 'json 或 xml', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'search',
      params: { query: 'COVID-19', format: 'json', pageSize: '1' },
      expect: { contains: 'resultList' },
    },
  },
  {
    id: 'biorxiv',
    name: 'bioRxiv/medRxiv API',
    category: 'literature',
    baseUrl: 'https://api.biorxiv.org',
    description: '预印本服务器元数据：按日期区间列文章与已发表对照',
    homepage: 'https://www.biorxiv.org/',
    docsUrl: 'https://api.biorxiv.org/',
    endpoints: [
      {
        id: 'details',
        name: '按日期列文章',
        method: 'GET',
        path: '/details/{server}/{from}/{to}/{cursor}',
        description: '列某服务器在日期区间内的预印本元数据',
        params: [
          { name: 'server', required: true, description: 'biorxiv 或 medrxiv', in: 'path' },
          { name: 'from', required: true, description: '起始日期，如 2024-06-01', in: 'path' },
          { name: 'to', required: true, description: '截止日期，如 2024-06-02', in: 'path' },
          { name: 'cursor', required: true, description: '分页游标，从 0 开始', in: 'path' },
        ],
      },
      {
        id: 'pubs',
        name: '已发表对照',
        method: 'GET',
        path: '/pubs/{server}/{from}/{to}/{cursor}',
        description: '列预印本与正式发表 DOI 的对照',
        params: [
          { name: 'server', required: true, description: 'biorxiv 或 medrxiv', in: 'path' },
          { name: 'from', required: true, description: '起始日期', in: 'path' },
          { name: 'to', required: true, description: '截止日期', in: 'path' },
          { name: 'cursor', required: true, description: '分页游标', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'details',
      params: { server: 'biorxiv', from: '2024-01-01', to: '2024-01-02', cursor: '0' },
      expect: { contains: 'messages' },
    },
  },
  {
    id: 'crossref',
    name: 'CrossRef REST',
    category: 'literature',
    baseUrl: 'https://api.crossref.org',
    description: 'CrossRef DOI 元数据：按 DOI 取记录、按关键词检索',
    homepage: 'https://www.crossref.org/',
    docsUrl: 'https://api.crossref.org/swagger-ui/index.html',
    endpoints: [
      {
        id: 'work',
        name: '按 DOI 取记录',
        method: 'GET',
        path: '/works/{doi}',
        description: '按 DOI 取文献元数据（DOI 中的 / 会被自动 URL 编码）',
        params: [{ name: 'doi', required: true, description: '如 10.1038/171737a0', in: 'path' }],
      },
      {
        id: 'works',
        name: '文献检索',
        method: 'GET',
        path: '/works',
        description: '按关键词检索 DOI 记录',
        params: [
          { name: 'query', required: true, description: '关键词' },
          { name: 'rows', description: '返回条数，默认 20' },
          { name: 'select', description: '字段裁剪，如 DOI,title,author' },
        ],
      },
    ],
    probe: {
      endpoint: 'work',
      params: { doi: '10.1038/171737a0' },
      expect: { contains: '171737a0' },
    },
  },
  {
    id: 'openalex',
    name: 'OpenAlex API',
    category: 'literature',
    baseUrl: 'https://api.openalex.org',
    description: 'OpenAlex 开放学术图谱：文献、作者、机构、概念',
    homepage: 'https://openalex.org/',
    docsUrl: 'https://docs.openalex.org/',
    endpoints: [
      {
        id: 'works',
        name: '文献检索',
        method: 'GET',
        path: '/works',
        description: '检索学术文献（search 全文 / filter 结构化过滤）',
        params: [
          { name: 'search', description: '全文关键词，如 crispr' },
          { name: 'filter', description: '过滤式，如 doi:10.1038/171737a0' },
          { name: 'select', description: '字段裁剪（减小载荷），如 id,display_name' },
          { name: 'per-page', description: '每页条数，最大 200' },
        ],
      },
      {
        id: 'work',
        name: '单篇文献',
        method: 'GET',
        path: '/works/{id}',
        description: '按 OpenAlex ID（W 开头）或 https://doi.org/... 取文献详情',
        params: [{ name: 'id', required: true, description: '如 W2741809807', in: 'path' }],
      },
      {
        id: 'authors',
        name: '作者检索',
        method: 'GET',
        path: '/authors',
        description: '检索作者（h-index、机构、发文量）',
        params: [
          { name: 'search', required: true, description: '作者名' },
          { name: 'per-page', description: '每页条数' },
        ],
      },
    ],
    probe: {
      endpoint: 'works',
      params: { filter: 'doi:10.1038/nature14573', select: 'id,display_name' },
      expect: { contains: 'display_name' },
    },
  },
  {
    id: 'doaj',
    name: 'DOAJ 开放获取期刊',
    category: 'literature',
    baseUrl: 'https://doaj.org',
    description: '开放获取期刊与文章检索目录（替代 Semantic Scholar——后者无 key 时限流频繁）',
    homepage: 'https://doaj.org/',
    docsUrl: 'https://doaj.org/api/v4/docs',
    endpoints: [
      {
        id: 'search-articles',
        name: '文章检索',
        method: 'GET',
        path: '/api/search/articles/{query}',
        description: '按关键词/DOI 检索开放获取文章',
        params: [
          { name: 'query', required: true, description: '检索词或 doi:10.xxxx', in: 'path' },
        ],
      },
      {
        id: 'search-journals',
        name: '期刊检索',
        method: 'GET',
        path: '/api/search/journals/{query}',
        description: '按关键词检索 OA 期刊',
        params: [
          { name: 'query', required: true, description: '检索词', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'search-journals',
      params: { query: 'bioinformatics' },
      expect: { contains: 'results' },
    },
  },
  {
    id: 'icite',
    name: 'NIH iCite API',
    category: 'literature',
    baseUrl: 'https://icite.od.nih.gov/api',
    description: 'NIH iCite 引文指标：按 PMID 取引用数与 RCR 指标',
    homepage: 'https://icite.od.nih.gov/',
    docsUrl: 'https://icite.od.nih.gov/api',
    endpoints: [
      {
        id: 'pubs',
        name: '批量引文指标',
        method: 'GET',
        path: '/pubs',
        description: '按逗号分隔 PMID 列表取引用数、RCR 等（上限约 1000 个）',
        params: [{ name: 'pmids', required: true, description: '逗号分隔 PMID，如 23456777,27578104' }],
      },
      {
        id: 'pub-single',
        name: '单篇引文指标',
        method: 'GET',
        path: '/pubs',
        description: '单篇 PMID 的引用指标（pmids 传一个即可）',
        params: [{ name: 'pmids', required: true, description: '单个 PMID，如 23456777' }],
      },
    ],
    probe: {
      endpoint: 'pubs',
      params: { pmids: '23456777' },
      expect: { contains: 'pmid' },
    },
  },
  {
    id: 'mgnify',
    name: 'MGnify API',
    category: 'microbes',
    baseUrl: 'https://www.ebi.ac.uk/metagenomics/api/v1',
    description: 'MGnify 宏基因组/微生物组数据分析存档：研究、样本、分析任务（API 已从 /mgnify 迁至 /metagenomics 路径）',
    homepage: 'https://www.ebi.ac.uk/mgnify/',
    docsUrl: 'https://docs.mgnify.org/src/docs/api.html',
    endpoints: [
      {
        id: 'studies',
        name: '研究列表',
        method: 'GET',
        path: '/studies',
        description: '分页列出宏基因组研究（JSON:API）',
        params: [{ name: 'page_size', description: '每页条数' }],
      },
      {
        id: 'study',
        name: '研究详情',
        method: 'GET',
        path: '/studies/{accession}',
        description: '按 MGYS 登录号取宏基因组研究',
        params: [{ name: 'accession', required: true, description: '如 MGYS00000462', in: 'path' }],
      },
      {
        id: 'sample',
        name: '样本详情',
        method: 'GET',
        path: '/samples/{accession}',
        description: '按样本登录号取样本元数据',
        params: [{ name: 'accession', required: true, description: '样本登录号', in: 'path' }],
      },
      {
        id: 'biome-root',
        name: 'biome 根节点',
        method: 'GET',
        path: '/biomes/root',
        description: '取 biome 分类树根（浏览研究的入口）',
      },
    ],
    probe: {
      endpoint: 'studies',
      params: { page_size: '1' },
      expect: { contains: 'studies' },
    },
  },
  {
    id: 'gtdb',
    name: 'GTDB API',
    category: 'microbes',
    baseUrl: 'https://gtdb-api.ecogenomic.org',
    description: 'GTDB 基因组分类数据库：原核生物标准化基因组分类',
    homepage: 'https://gtdb.ecogenomic.org/',
    docsUrl: 'https://github.com/Ecogenomics/api.gtdb.ecogenomic.org',
    endpoints: [
      {
        id: 'taxon-search',
        name: '分类检索',
        method: 'GET',
        path: '/taxon/search/{query}',
        description: '按部分名称检索分类单元（d__/p__/c__/o__/f__/g__/s__ 前缀命名）',
        params: [
          { name: 'query', required: true, description: '如 Escherichia', in: 'path' },
          { name: 'limit', description: '返回条数上限，最大 100' },
        ],
      },
      {
        id: 'species',
        name: '物种簇详情',
        method: 'GET',
        path: '/species/search/{species}',
        description: '按物种名取物种簇与其基因组列表（大小写敏感，如 Akkermansia muciniphila）',
        params: [{ name: 'species', required: true, description: '物种名（不带 s__ 前缀）', in: 'path' }],
      },
      {
        id: 'taxon-card',
        name: '分类卡片',
        method: 'GET',
        path: '/taxon/{taxon}/card',
        description: '取分类单元卡片（等级、基因组数、上层分类）',
        params: [{ name: 'taxon', required: true, description: '如 g__Escherichia', in: 'path' }],
      },
      {
        id: 'genome-card',
        name: '基因组卡片',
        method: 'GET',
        path: '/genome/{accession}/card',
        description: '按基因组登录号（GCA_/GCF_）取详细元数据与 GTDB 分类',
        params: [{ name: 'accession', required: true, description: '如 GCA_000005845.2', in: 'path' }],
      },
    ],
    probe: {
      endpoint: 'taxon-search',
      params: { query: 'Escherichia', limit: '5' },
      expect: { contains: 'matches' },
    },
  },
  {
    id: 'bvbrc',
    name: 'BV-BRC Data API',
    category: 'microbes',
    baseUrl: 'https://www.bv-brc.org/api',
    description: 'BV-BRC（原 PATRIC）细菌病毒生物信息资源中心：基因组与特征查询（RQL 语法）',
    homepage: 'https://www.bv-brc.org/',
    docsUrl: 'https://www.bv-brc.org/docs/',
    authNote: '查询用 RQL 语法（eq()/keyword()/limit()）；路径模板已内嵌常用写法，参数值会被 URL 编码',
    endpoints: [
      {
        id: 'genome',
        name: '按 ID 查基因组',
        method: 'GET',
        path: '/genome/?eq(genome_id,{genomeId})&limit({limit})',
        description: '按基因组 ID 取基因组元数据',
        params: [
          { name: 'genomeId', required: true, description: '如 83332.12（E. coli K-12）', in: 'path' },
          { name: 'limit', description: '返回条数，默认 25', in: 'path' },
        ],
      },
      {
        id: 'genome-search',
        name: '基因组检索',
        method: 'GET',
        path: '/genome/?keyword({keyword})&limit({limit})',
        description: '按关键词检索基因组',
        params: [
          { name: 'keyword', required: true, description: '如 Escherichia coli', in: 'path' },
          { name: 'limit', description: '返回条数，默认 25', in: 'path' },
        ],
      },
      {
        id: 'genome-feature',
        name: '基因组特征',
        method: 'GET',
        path: '/genome_feature/?eq(genome_id,{genomeId})&limit({limit})',
        description: '列某基因组的注释特征（CDS 等，分页）',
        params: [
          { name: 'genomeId', required: true, description: '基因组 ID', in: 'path' },
          { name: 'limit', description: '返回条数，默认 25', in: 'path' },
        ],
      },
    ],
    probe: {
      endpoint: 'genome',
      params: { genomeId: '83332.12', limit: '1' },
      expect: { contains: '83332' },
    },
  },
];

const serviceIndex = new Map(WEB_API_SERVICES.map(service => [service.id, service]));

export function getWebApiService(id: string): WebApiService | undefined {
  return serviceIndex.get(id);
}

export function getWebApiEndpoint(
  service: WebApiService,
  endpointId: string,
): WebApiEndpoint | undefined {
  return service.endpoints.find(endpoint => endpoint.id === endpointId);
}
