#!/usr/bin/env python3
"""Build a pinned ENCODE chip-seq-pipeline2 input JSON from a simple lane TSV."""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sample-sheet", required=True)
    parser.add_argument("--genome-tsv", required=True)
    parser.add_argument("--genome-name", required=True)
    parser.add_argument("--title", required=True)
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def usable_path(value: str) -> bool:
    return value.startswith(("http://", "https://", "s3://", "gs://")) or os.path.isabs(value)


def main() -> int:
    args = parse_args()
    grouped: dict[tuple[str, int], dict[str, list[str]]] = defaultdict(lambda: {"r1": [], "r2": []})
    with open(args.sample_sheet, newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        required = {"type", "replicate", "read1", "read2"}
        if not reader.fieldnames or not required.issubset(set(reader.fieldnames)):
            raise ValueError("样本表必须包含 type、replicate、read1、read2 四列")
        for row_number, row in enumerate(reader, start=2):
            sample_type = (row.get("type") or "").strip().lower()
            if sample_type not in {"chip", "control"}:
                raise ValueError(f"第 {row_number} 行 type 必须是 chip 或 control")
            try:
                replicate = int((row.get("replicate") or "").strip())
            except ValueError as exc:
                raise ValueError(f"第 {row_number} 行 replicate 必须是 1-10 的整数") from exc
            if replicate < 1 or replicate > 10:
                raise ValueError(f"第 {row_number} 行 replicate 必须是 1-10")
            read1 = (row.get("read1") or "").strip()
            read2 = (row.get("read2") or "").strip()
            if not read1 or not usable_path(read1):
                raise ValueError(f"第 {row_number} 行 read1 必须是绝对路径或受支持 URI")
            if read2 and not usable_path(read2):
                raise ValueError(f"第 {row_number} 行 read2 必须是绝对路径或受支持 URI")
            grouped[(sample_type, replicate)]["r1"].append(read1)
            if read2:
                grouped[(sample_type, replicate)]["r2"].append(read2)

    chip_reps = sorted(rep for sample_type, rep in grouped if sample_type == "chip")
    control_reps = sorted(rep for sample_type, rep in grouped if sample_type == "control")
    if not chip_reps:
        raise ValueError("样本表至少需要一个 chip 生物学重复")
    if not control_reps:
        raise ValueError("TF ChIP 的官方默认 SPP 峰调用需要至少一个 control 重复")
    if chip_reps != list(range(1, len(chip_reps) + 1)):
        raise ValueError("chip replicate 必须从 1 开始连续编号")
    if control_reps != list(range(1, len(control_reps) + 1)):
        raise ValueError("control replicate 必须从 1 开始连续编号")

    paired_states = {bool(reads["r2"]) for reads in grouped.values()}
    if len(paired_states) != 1:
        raise ValueError("同一次官方流程不能混合单端与双端文库")
    paired = paired_states.pop()
    for key, reads in grouped.items():
        if paired and len(reads["r1"]) != len(reads["r2"]):
            raise ValueError(f"{key[0]} replicate {key[1]} 的 R1/R2 lane 数不一致")

    genome_tsv = args.genome_tsv
    if not usable_path(genome_tsv):
        raise ValueError("genome TSV 必须是绝对路径或受支持 URI")
    payload: dict[str, object] = {
        "chip.title": args.title,
        "chip.description": "Generated by HPClaw for the official ENCODE-DCC chip-seq-pipeline2 v2.2.2",
        "chip.pipeline_type": "tf",
        "chip.peak_caller": "spp",
        "chip.paired_end": paired,
        "chip.genome_tsv": genome_tsv,
        "chip.genome_name": args.genome_name,
        "chip.idr_thresh": 0.05,
        "chip.true_rep_only": False,
        "chip.always_use_pooled_ctl": True,
    }
    for (sample_type, replicate), reads in sorted(grouped.items()):
        prefix = "chip.fastqs" if sample_type == "chip" else "chip.ctl_fastqs"
        payload[f"{prefix}_rep{replicate}_R1"] = reads["r1"]
        if paired:
            payload[f"{prefix}_rep{replicate}_R2"] = reads["r2"]

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {output}: {len(chip_reps)} ChIP biological replicate(s), {len(control_reps)} control(s), paired_end={paired}")
    if len(chip_reps) == 1:
        print("WARNING: one biological replicate: official pipeline will rely on self-pseudoreplicate reproducibility", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
